---
resources:
  - name: springboot-app
    type: git
    source:
      uri: https://github.com/rishipathak/spring-boot-maven-example-helloworld.git
      branch: master
      username: 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
      password: x-oauth-basic

jobs:
  - name: build
    serial: true
    plan:
      - get:  springboot-app
        trigger: true
      - task: mvn-build
        privileged: true
        file: springboot-app/build.yml